server: #서버포트설정
     port: 7070
spring:
  datasource:
#    batch:
#      hikari:
#        jdbc-url: jdbc:mysql://localhost:3306/gsw?serverTimezone=Asia/Seoul
#        username: root
#        password: gongsik1204
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        pool-name: 'read-and-write-pool'
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gsw?serverTimezone=Asia/Seoul
    username: root
    password: gongsik1204   
  jpa:
   database-platform: org.hibernate.dialect.MySQLDialect
   hibernate:
    ddl-auto: none
   properties:
    hibernate:
     use_sql_comments: true  # sql 쿼리의 추가정보를 보여줍니다.
     format_sql: true  # sql query formatting
     dialect: org.hibernate.dialect.MySQL8Dialect
